services:
  - type: web
    name: neevachi-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://neevachi41_db_user:Pranit19702006@cluster0.l3whoaz.mongodb.net/?appName=Cluster0
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://neevachi-solutions.vercel.app
      - key: PORT
        value: 10000
